# Generated by Django 4.1.5 on 2023-01-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('thermal_conductivity', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField(max_length=10)),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UCalculator.composite')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UCalculator.material')),
            ],
        ),
    ]
