# Generated by Django 4.1.5 on 2023-01-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='thickness',
            field=models.IntegerField(),
        ),
    ]
