# Generated by Django 4.1.5 on 2023-01-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='composite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UCalculator.composite'),
        ),
    ]
