# Generated by Django 4.1.5 on 2023-02-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCalculator', '0007_alter_composite_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='thermal_conductivity',
            new_name='K_value',
        ),
    ]
